# Generated by Django 5.2.4 on 2025-07-30 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.customer'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='price',
            field=models.FloatField(default=200, null=True),
        ),
    ]
